# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(270, 370)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Reload = QtWidgets.QPushButton(Form)
        self.Reload.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setFamily("fontello")
        self.Reload.setFont(font)
        self.Reload.setObjectName("Reload")
        self.verticalLayout.addWidget(self.Reload)
        self.listBE = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setFamily("fontello")
        self.listBE.setFont(font)
        self.listBE.setObjectName("listBE")
        self.verticalLayout.addWidget(self.listBE)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Open = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("fontello")
        self.Open.setFont(font)
        self.Open.setObjectName("Open")
        self.horizontalLayout.addWidget(self.Open)
        self.More = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("fontello")
        self.More.setFont(font)
        self.More.setObjectName("More")
        self.horizontalLayout.addWidget(self.More)
        self.Save = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("fontello")
        self.Save.setFont(font)
        self.Save.setObjectName("Save")
        self.horizontalLayout.addWidget(self.Save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Myndustry Lanch DL v0.3"))
        self.Reload.setText(_translate("Form", "Reload"))
        self.Open.setText(_translate("Form", "Open"))
        self.More.setText(_translate("Form", "More"))
        self.Save.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
